### ISSUE TITLE
i need read data for offline mode for xbox game pass

### ISSUE THREAD

**Issue by Supertarxr** [Mazzzoni/b4bstats#14]
after playing mom It's gone but I don't know which missions I missed in Nightmare mode in offline mode.

**Comment by Mazzzoni** [comment]
Hello, thanks for reaching out, sadly offline can't be added to the app as of now because the statistics file you drag n' drop into the tool doesn't contain offline data :(
We can expect TRS devs to make it available in the future hopefully!
