### ISSUE TITLE
Seperate Swarm and Campaign stats

### ISSUE THREAD

**Issue by Jennicide45** [Mazzzoni/b4bstats#32]
Dunno how possible it would be to have the stat breakdown more seperated by swarm and campaign, if the game even tracks the values seperately. Would love to see dmg/round healing/round on swarm.

**Comment by Mazzzoni** [comment]
Hello,
Well sadly the way the stats are tracked into the stats file makes it impossible to tell which are from campaign and which are from swarm. :(
Hopefully this maybe getting adjusted in future stats file versions so this would allow third party apps to do that !
