### ISSUE TITLE
B4BSTATS Can't save play statistics.

### ISSUE THREAD

**Issue by pinny2532** [Mazzzoni/b4bstats#50]
B4BSTATS Can't save play statistics.

**Comment by Mazzzoni** [comment]
Hello Pinny,
Can you give more details about your issue ? Without further information, I cannot help you sadly...

**Comment by pinny2532** [comment]
[image: image.png]

Finished the game but each level of the game doesn't save statistics
for you. It's as if I haven't played that level yet.


ในวันที่ อา. 9 เม.ย. 2023 เวลา 18:38 Mazz ***@***.***>
เขียนว่า:

**Comment by Mazzzoni** [comment]
Well, it happens that the game itself sometimes does not save your progression correctly, if this happen, you have to re-do the level sadly...
Also make sure to upload the up to date save file so you can see the difference after each completion.
I wish you a nice day!
